server:
  port: 9000
spring:
  application:
    name: sbm-forex-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sbm_beer_service;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sags
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console